INSERT INTO `UserCase` VALUES (  1,'createEvent');
INSERT INTO `UserCase` VALUES (  2,'changeEventData');
INSERT INTO `UserCase` VALUES (  3,'addParticipantToEvent');
INSERT INTO `UserCase` VALUES (  4,'removeParticipantFromEvent');
INSERT INTO `UserCase` VALUES (  5,'setPaid');
INSERT INTO `UserCase` VALUES (  6,'changeRegistrationState ');
INSERT INTO `UserCase` VALUES (  7,'findEventByName');
INSERT INTO `UserCase` VALUES (  8,'addActivity');
INSERT INTO `UserCase` VALUES (  9,'removeActivity');
INSERT INTO `UserCase` VALUES ( 10,'changeActivityData');
INSERT INTO `UserCase` VALUES ( 11,'setActivityOrganizer');
INSERT INTO `UserCase` VALUES ( 12,'addParticipantToActivity');
INSERT INTO `UserCase` VALUES ( 13,'removeParticipantFromActivity');
INSERT INTO `UserCase` VALUES ( 14,'getActivityParticipants');
INSERT INTO `UserCase` VALUES ( 15,'addNews');
INSERT INTO `UserCase` VALUES ( 16,'changeNewsData');
INSERT INTO `UserCase` VALUES ( 17,'getLastNews');
INSERT INTO `UserCase` VALUES ( 18,'removeNews');
INSERT INTO `UserCase` VALUES ( 19,'addUser');
INSERT INTO `UserCase` VALUES ( 20,'changeUserData');
INSERT INTO `UserCase` VALUES ( 21,'changeUserPassword');
INSERT INTO `UserCase` VALUES ( 22,'getUsersByEvent');
INSERT INTO `UserCase` VALUES ( 23,'getAllUsers');
INSERT INTO `UserCase` VALUES ( 24,'findUsersByName');
INSERT INTO `UserCase` VALUES ( 25,'addUserToBlackList');
INSERT INTO `UserCase` VALUES ( 26,'removeUserFromBlackList');
INSERT INTO `UserCase` VALUES ( 27,'getBlacklistedUsers');
INSERT INTO `UserCase` VALUES ( 28,'setDefaultLanguage');
INSERT INTO `UserCase` VALUES ( 29,'removeUser');
INSERT INTO `UserCase` VALUES ( 30,'createRole');
INSERT INTO `UserCase` VALUES ( 31,'addRole');
INSERT INTO `UserCase` VALUES ( 32,'removeRole');
INSERT INTO `UserCase` VALUES ( 33,'getUserRoles');
INSERT INTO `UserCase` VALUES ( 34,'getAllRoles');
INSERT INTO `UserCase` VALUES ( 35,'createUseCase');
INSERT INTO `UserCase` VALUES ( 36,'addPermission');
INSERT INTO `UserCase` VALUES ( 37,'removePermission');
INSERT INTO `UserCase` VALUES ( 38,'getRolePermissions');
INSERT INTO `UserCase` VALUES ( 39,'getAllUseCases');
INSERT INTO `UserCase` VALUES ( 40,'USERaddParticipantToEvent');
INSERT INTO `UserCase` VALUES ( 41,'USERremoveParticipantFromEvent');

INSERT INTO `Role` VALUES (  1,'SuperAdmin');

INSERT INTO `Role_UserCase` VALUES (  1,  1, 1);
INSERT INTO `Role_UserCase` VALUES (  2,  2, 1);
INSERT INTO `Role_UserCase` VALUES (  3,  3, 1);
INSERT INTO `Role_UserCase` VALUES (  4,  4, 1);
INSERT INTO `Role_UserCase` VALUES (  5,  5, 1);
INSERT INTO `Role_UserCase` VALUES (  6,  6, 1);
INSERT INTO `Role_UserCase` VALUES (  7,  7, 1);
INSERT INTO `Role_UserCase` VALUES (  8,  8, 1);
INSERT INTO `Role_UserCase` VALUES (  9,  9, 1);
INSERT INTO `Role_UserCase` VALUES ( 10, 10, 1);
INSERT INTO `Role_UserCase` VALUES ( 11, 11, 1);
INSERT INTO `Role_UserCase` VALUES ( 12, 12, 1);
INSERT INTO `Role_UserCase` VALUES ( 13, 13, 1);
INSERT INTO `Role_UserCase` VALUES ( 14, 14, 1);
INSERT INTO `Role_UserCase` VALUES ( 15, 15, 1);
INSERT INTO `Role_UserCase` VALUES ( 16, 16, 1);
INSERT INTO `Role_UserCase` VALUES ( 17, 17, 1);
INSERT INTO `Role_UserCase` VALUES ( 18, 18, 1);
INSERT INTO `Role_UserCase` VALUES ( 19, 19, 1);
INSERT INTO `Role_UserCase` VALUES ( 20, 20, 1);
INSERT INTO `Role_UserCase` VALUES ( 21, 21, 1);
INSERT INTO `Role_UserCase` VALUES ( 22, 22, 1);
INSERT INTO `Role_UserCase` VALUES ( 23, 23, 1);
INSERT INTO `Role_UserCase` VALUES ( 24, 24, 1);
INSERT INTO `Role_UserCase` VALUES ( 25, 25, 1);
INSERT INTO `Role_UserCase` VALUES ( 26, 26, 1);
INSERT INTO `Role_UserCase` VALUES ( 27, 27, 1);
INSERT INTO `Role_UserCase` VALUES ( 28, 28, 1);
INSERT INTO `Role_UserCase` VALUES ( 29, 29, 1);
INSERT INTO `Role_UserCase` VALUES ( 30, 30, 1);
INSERT INTO `Role_UserCase` VALUES ( 31, 31, 1);
INSERT INTO `Role_UserCase` VALUES ( 32, 32, 1);
INSERT INTO `Role_UserCase` VALUES ( 33, 33, 1);
INSERT INTO `Role_UserCase` VALUES ( 34, 34, 1);
INSERT INTO `Role_UserCase` VALUES ( 35, 35, 1);
INSERT INTO `Role_UserCase` VALUES ( 36, 36, 1);
INSERT INTO `Role_UserCase` VALUES ( 37, 37, 1);
INSERT INTO `Role_UserCase` VALUES ( 38, 38, 1);
INSERT INTO `Role_UserCase` VALUES ( 39, 39, 1);
INSERT INTO `Role_UserCase` VALUES ( 40, 40, 1);
INSERT INTO `Role_UserCase` VALUES ( 41, 41, 1);